using System;
using System.Collections.Generic;

namespace MaddenDataScraper_2024
{
	public class DataFormat
	{
		public static readonly List<String> MaddenImportFormat = new List<string> {
		"team",
			"firstName",
			"lastName",
			"position",
			"jerseyNum",
			"overall_rating",
			"speed_rating",
			"acceleration_rating",
			"strength_rating",
			"agility_rating",
			"awareness_rating",
			"catching_rating",
			"carrying_rating",
			"throwPower_rating",
			//"throwAccuracy_rating",
            "throwAccuracyShort_rating","throwAccuracyMid_rating", "throwAccuracyDeep_rating",
			"kickPower_rating",
			"kickAccuracy_rating",
			"runBlock_rating",
			"passBlock_rating",
			"tackle_rating",
			"jumping_rating",
			"kickReturn_rating",
			"injury_rating",
			"stamina_rating",
			"toughness_rating",
			"trucking_rating",
			"finesseMoves_rating",// replaces -> "elusiveness_rating",
			"bCVision_rating",
			"stiffArm_rating",
			"spinMove_rating",
			"jukeMove_rating",
			"impactBlocking_rating",
			"powerMoves_rating",
			//"finesseMoves_rating", // dup
			"blockShedding_rating",
			"pursuit_rating",
			"playRecognition_rating",
			"manCoverage_rating",
			"zoneCoverage_rating",
			"spectacularCatch_rating",
			"catchInTraffic_rating",
			//"routeRunning_rating",
            "mediumRouteRunning_rating", "deepRouteRunning_rating", "shortRouteRunning_rating",
			"hitPower_rating",
			"press_rating",
			"release_rating",
			"playAction_rating",
			"throwOnTheRun_rating",
			"height",
			"weight",

			/* these were not used in 2016
			"age",
			"runBlockStrength_rating",
			"runBlockFootwork_rating",
			"passBlockStrength_rating",
			"passBlockFootwork_rating",*/

			//* these are new for 2018
			"yearsPro",
			//"totalSalary",
			//"signingBonus",
			"plyrBirthdate",
			"plyrHandedness",
			"college"
			};

		public static readonly string[] MaddenExportFormat = {
			"team",
			"firstName",
			"lastName",
			"position",
			"jerseyNum",
			"overall_rating",
			"speed_rating",
			"acceleration_rating",
			"strength_rating",
			"agility_rating",
			"awareness_rating",
			"catching_rating",
			"carrying_rating",
			"throwPower_rating",
			"throwAccuracy_rating",
			"throwAccuracyShort_rating",
			"throwAccuracyMid_rating",
			"throwAccuracyDeep_rating",
			"kickPower_rating",
			"kickAccuracy_rating",
			"runBlock_rating",
			"passBlock_rating",
			"tackle_rating",
			"jumping_rating",
			"kickReturn_rating",
			"injury_rating",
			"stamina_rating",
			"toughness_rating",
			"trucking_rating",
			"finesseMoves_rating",// replaces -> "elusiveness_rating",
			"bCVision_rating",
			"stiffArm_rating",
			"spinMove_rating",
			"jukeMove_rating",
			"impactBlocking_rating",
			"powerMoves_rating",
			"finesseMoves_rating",
			"blockShedding_rating",
			"pursuit_rating",
			"playRecognition_rating",
			"manCoverage_rating",
			"zoneCoverage_rating",
			"spectacularCatch_rating",
			"catchInTraffic_rating",
			"routeRunning_rating",
			"hitPower_rating",
			"press_rating",
			"release_rating",
			"playAction_rating",
			"throwOnTheRun_rating",
			"height",
			"weight",

			/* these were not used in 2016
			"age",
			"runBlockStrength_rating",
			"runBlockFootwork_rating",
			"passBlockStrength_rating",
			"passBlockFootwork_rating",*/

			//* these are new for 2018
			"yearsPro",
			"totalSalary",
			"signingBonus",
			"plyrBirthdate",
			"plyrHandedness",
			"college",
		};
	}
}
